// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscoverDevices(arg1) {
  return window['go']['main']['App']['DiscoverDevices'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Install(arg1) {
  return window['go']['main']['App']['Install'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Provision(arg1) {
  return window['go']['main']['App']['Provision'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function TestSSH(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestSSH'](arg1, arg2, arg3, arg4);
}

export function Verify(arg1) {
  return window['go']['main']['App']['Verify'](arg1);
}
