// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {gateway} from '../models';
import {discover} from '../models';
import {config} from '../models';
import {device} from '../models';

export function ApplyRegistry(arg1:boolean):Promise<main.ApplyRegistryResult>;

export function CreateCapability(arg1:gateway.Capability):Promise<gateway.Capability>;

export function CreateDeviceFamily(arg1:gateway.DeviceFamily):Promise<gateway.DeviceFamily>;

export function CreateDeviceType(arg1:gateway.DeviceType):Promise<gateway.DeviceType>;

export function CreateEntitlement(arg1:gateway.Entitlement):Promise<gateway.Entitlement>;

export function CreatePlan(arg1:gateway.Plan):Promise<gateway.Plan>;

export function DiscoverDevices(arg1:string,arg2:boolean):Promise<Array<discover.Candidate>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetSession():Promise<main.SessionInfo>;

export function Install(arg1:main.InstallRequest):Promise<device.InstallResult>;

export function ListCapabilities():Promise<Array<gateway.Capability>>;

export function ListDeviceFamilies():Promise<Array<gateway.DeviceFamily>>;

export function ListDeviceTypes():Promise<Array<gateway.DeviceType>>;

export function ListEntitlements():Promise<Array<gateway.Entitlement>>;

export function ListPlans():Promise<Array<gateway.Plan>>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;

export function Logout():Promise<void>;

export function PatchEntitlement(arg1:string,arg2:gateway.EntitlementPatch):Promise<gateway.Entitlement>;

export function PatchPlan(arg1:string,arg2:gateway.PlanPatch):Promise<gateway.Plan>;

export function Provision(arg1:main.ProvisionRequest):Promise<main.ProvisionResult>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function TestSSH(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function Verify(arg1:main.VerifyRequest):Promise<main.VerifyResult>;
