// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyRegistry(arg1) {
  return window['go']['main']['App']['ApplyRegistry'](arg1);
}

export function CreateCapability(arg1) {
  return window['go']['main']['App']['CreateCapability'](arg1);
}

export function CreateDeviceFamily(arg1) {
  return window['go']['main']['App']['CreateDeviceFamily'](arg1);
}

export function CreateDeviceType(arg1) {
  return window['go']['main']['App']['CreateDeviceType'](arg1);
}

export function CreateEntitlement(arg1) {
  return window['go']['main']['App']['CreateEntitlement'](arg1);
}

export function CreatePlan(arg1) {
  return window['go']['main']['App']['CreatePlan'](arg1);
}

export function DiscoverDevices(arg1, arg2) {
  return window['go']['main']['App']['DiscoverDevices'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function Install(arg1) {
  return window['go']['main']['App']['Install'](arg1);
}

export function ListCapabilities() {
  return window['go']['main']['App']['ListCapabilities']();
}

export function ListDeviceFamilies() {
  return window['go']['main']['App']['ListDeviceFamilies']();
}

export function ListDeviceTypes() {
  return window['go']['main']['App']['ListDeviceTypes']();
}

export function ListEntitlements() {
  return window['go']['main']['App']['ListEntitlements']();
}

export function ListPlans() {
  return window['go']['main']['App']['ListPlans']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PatchEntitlement(arg1, arg2) {
  return window['go']['main']['App']['PatchEntitlement'](arg1, arg2);
}

export function PatchPlan(arg1, arg2) {
  return window['go']['main']['App']['PatchPlan'](arg1, arg2);
}

export function Provision(arg1) {
  return window['go']['main']['App']['Provision'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function TestSSH(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestSSH'](arg1, arg2, arg3, arg4);
}

export function Verify(arg1) {
  return window['go']['main']['App']['Verify'](arg1);
}
