// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {discover} from '../models';
import {config} from '../models';
import {main} from '../models';
import {device} from '../models';
import {gateway} from '../models';

export function DiscoverDevices(arg1:string,arg2:boolean):Promise<Array<discover.Candidate>>;

export function GetConfig():Promise<config.AppConfig>;

export function Install(arg1:main.InstallRequest):Promise<device.InstallResult>;

export function ListDeviceTypes():Promise<Array<gateway.DeviceType>>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;

export function Provision(arg1:main.ProvisionRequest):Promise<main.ProvisionResult>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function TestSSH(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function Verify(arg1:main.VerifyRequest):Promise<main.VerifyResult>;
